name: build

on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [2.12.14, 2.13.5]
        java: [adopt@1.8]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v2

    - name: Set up Java and Scala
      uses: olafurpg/setup-scala@v13
      with:
        java-version: ${{ matrix.java }}

    - name: Cache sbt
      uses: actions/cache@v2
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.coursier/cache/v1
          ~/.cache/coursier/v1
          ~/AppData/Local/Coursier/Cache/v1
          ~/Library/Caches/Coursier/v1
        key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

    - name: Test
      run: sbt ++${{ matrix.scala }} clean coverage test scalafmtCheckAll scalafmtSbtCheck "scalafixAll --check"

    - name: Coverage
      run: sbt ++${{ matrix.scala }} coverageReport

    - name: Send coverage report to codecov
      uses: codecov/codecov-action@v1

#    - name: Send coverage report to codacy
#      uses: codacy/codacy-coverage-reporter-action@master
